# Generated by Django 3.2 on 2021-11-04 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyacar', '0002_auto_20211101_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyacar',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='buyacar',
            name='body',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Truck', 'Truck'), ('Pick up', 'Pick up'), ('Van', 'Van'), ('Sedan', 'Sedan'), ('Bus', 'Bus'), ('Min Van', 'Min Van'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Min Bus', 'Min Bus'), ('Machinery', 'Machinery'), ('Forklift', 'Forklift'), ('Tractor', 'Tractor'), ('Motorcycle', 'Motorcycle'), ('Tricycle', 'Tricycle')], default='SUV', max_length=60, verbose_name='Body Type'),
        ),
        migrations.AlterField(
            model_name='buyacar',
            name='car_status',
            field=models.CharField(choices=[('Used Japan', 'Used Japan'), ('Used Tanzania', 'Used Tanzania'), ('New', 'New')], default='Used', max_length=50, verbose_name='Car status'),
        ),
    ]
