# Generated by Django 3.2 on 2021-10-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone', models.CharField(max_length=14, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='')),
                ('registration', models.CharField(help_text='Eg T 123 DGV', max_length=50, verbose_name='Registratin Number')),
                ('registration_year', models.IntegerField(help_text='Eg 2008', verbose_name='Year of registratin')),
                ('make', models.CharField(choices=[('Toyota', 'Toyota'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Jaguar', 'Jaguar'), ('KIA', 'KIA'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedes', 'Mercedes'), ('Porsche', 'Porsche'), ('Others', 'Others')], max_length=50, verbose_name='Make')),
                ('model', models.CharField(help_text='Eg Crown', max_length=50, verbose_name='Make')),
                ('milage', models.IntegerField(verbose_name='Mileage')),
                ('color', models.CharField(help_text='Eg Dark Blue', max_length=50, verbose_name='Color')),
                ('trans', models.CharField(choices=[('AT', 'AUTOMATIC'), ('Mn', 'Manual')], max_length=50, verbose_name='Transmission')),
                ('price', models.IntegerField(verbose_name='Expected Price in TSH')),
                ('description', models.TextField(verbose_name='Car description')),
                ('addion', models.TextField(verbose_name='Addion Details')),
            ],
            options={
                'verbose_name': 'Cars that are sold',
                'verbose_name_plural': 'Cars that are solds',
            },
        ),
    ]
