# Generated by Django 3.2 on 2021-10-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellyourcar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientCars',
            new_name='ClientCar',
        ),
    ]
