# Generated by Django 3.2 on 2021-11-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellyourcar', '0002_rename_clientcars_clientcar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcar',
            options={'verbose_name': 'Car for sale', 'verbose_name_plural': 'Cars for sale'},
        ),
    ]
