# Generated by Django 3.2 on 2021-11-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campain', models.CharField(max_length=120, verbose_name='campaign name')),
                ('slogan', models.CharField(max_length=120, verbose_name='slogan')),
                ('image', models.ImageField(help_text='Height and width must be 1000px x 1000px', upload_to='advert/image/')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Campaigns model',
                'verbose_name_plural': 'Campaigns models',
            },
        ),
    ]
