# Generated by Django 3.2 on 2021-11-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsmodel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
