# Generated by Django 3.2 on 2021-10-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120, verbose_name='car brand name')),
                ('logo', models.ImageField(upload_to='car/logo/')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Car Manufacture',
                'verbose_name_plural': 'Car Manufactures',
            },
        ),
        migrations.CreateModel(
            name='SellCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='photo_path')),
                ('model', models.CharField(max_length=50, verbose_name='Car Model')),
                ('color', models.CharField(max_length=50, verbose_name='Color of the car')),
                ('trans', models.CharField(choices=[('AT', 'AUTOMATIC'), ('Mn', 'Manual')], max_length=2, verbose_name='Transmision')),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Gas', 'Gas'), ('Electric', 'Electric'), ('Hibrid', 'Hibrid')], max_length=12, verbose_name='Fuel')),
                ('mileage', models.IntegerField(verbose_name='Milage')),
                ('engine', models.IntegerField(verbose_name='Engine size')),
                ('registered', models.IntegerField(verbose_name='Registered Year')),
                ('doors', models.IntegerField(verbose_name='Doors')),
                ('seats', models.IntegerField(verbose_name='Seats')),
                ('passenger', models.IntegerField(verbose_name='Passengers')),
                ('body', models.IntegerField(verbose_name='Body')),
                ('hand', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Default', 'Defaut')], max_length=12, verbose_name='Driving Hand')),
                ('drive', models.CharField(choices=[('2WD', '2WD'), ('4WD', '4WD'), ('AWD', 'AWD')], max_length=12, verbose_name='Drive')),
                ('available', models.BooleanField(default=True, verbose_name='Car is available')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellcar.carmodel', verbose_name='Brand Name')),
                ('features', models.ManyToManyField(to='sellcar.CarFeatures', verbose_name='features')),
            ],
            options={
                'verbose_name': 'SellCar',
                'verbose_name_plural': 'SellCars',
            },
        ),
    ]
