# Generated by Django 3.2 on 2021-10-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carfeatures',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car Manufacture', 'verbose_name_plural': 'Cars Manufactures'},
        ),
        migrations.AlterModelOptions(
            name='sellcar',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='sellcar',
            name='price',
            field=models.IntegerField(default=10, help_text='Enter price in USD', verbose_name='Cars Price'),
        ),
    ]
